
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://kgbycddsvpmcbdkludxt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtnYnljZGRzdnBtY2Jka2x1ZHh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5NDE4MjMsImV4cCI6MjA1OTUxNzgyM30.14vk8wWT-GezpHpscAz-6zyuNTzVEA10TldQz3IOBvw";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
